AllCops:
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity: 
  Enabled: false

Metrics/MethodLength:
  Max: 15

Naming/AccessorMethodName: 
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Alias:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
